# This is just a sample docker-compose.yml file. You can use it as a starting point for your own.
version: '3'
services:
  perforce:
    image: derkork/perforce-mini:latest
    restart: unless-stopped
    volumes:
      - ./p4dctl.conf.d:/etc/perforce/p4dctl.conf.d
      - ./perforce-data:/perforce-data
    environment:
      - P4PORT=1666
      - P4ROOT=/perforce-data
      - SERVER_ID=perforce
      - MASTER_USER=perforce-master
      - PERFORCE_UID=1000
      - PERFORCE_GID=1000
    ports:
      - 1666:1666
